export const ECONOMICS_DESCRIPTIONS: Record<string, { focus: string; example: string }> = {
  // Matrikulasi (4)
  "Uang": { focus: "Evolusi dan fungsi uang sebagai alat tukar, satuan hitung, dan penyimpan nilai resmi.", example: "Uang fiat, sistem kliring perbankan & likuiditas moneter (M1/M2)" },
  "Barter": { focus: "Sistem pertukaran langsung komoditas tanpa uang dan kendala kebetulan ganda (double coincidence of wants).", example: "Perdagangan barter hasil bumi tradisional antardaerah" },
  "Perputaran": { focus: "Kecepatan perputaran uang (velocity of money) dalam menggerakkan transaksi output riil.", example: "Persamaan Kuantitas Fisher: M × V = P × Y" },
  "Kelangkaan": { focus: "Prinsip dasar ilmu ekonomi: keterbatasan sumber daya relatif terhadap kebutuhan manusia yang tak terbatas.", example: "Trade-off & biaya peluang (opportunity cost) alokasi modal" },

  // 1 SKS (9)
  "Pelaku Ekonomi": { focus: "Empat sektor utama: rumah tangga konsumen, produsen/perusahaan, pemerintah, dan sektor eksternal.", example: "Interaksi 4 sektor dalam arus perekonomian makro" },
  "Pasar": { focus: "Mekanisme interaksi pembeli dan penjual untuk alokasi komoditas dan pembentukan harga wajar.", example: "Pasar komoditas fisik, bursa efek, dan pasar faktor produksi" },
  "Circular Flow": { focus: "Diagram arus melingkar pendapatan, balas jasa faktor produksi, serta aliran barang dan jasa.", example: "Arus pembayaran gaji, sewa tanah, bunga modal, dan profit usaha" },
  "Alur": { focus: "Jalur transmisi distribusi rantai pasok dari hulu produksi hingga ke konsumen akhir.", example: "Rantai pasok distribusi sembako dan logistik pangan nasional" },
  "Pemerintah": { focus: "Fungsi alokasi barang publik, distribusi pendapatan, dan stabilisasi makroekonomi negara.", example: "Pembangunan infrastruktur transportasi dan regulasi monopoli" },
  "Konsumsi": { focus: "Pola pengeluaran rumah tangga, teori utilitas, dan kecenderungan konsumsi marjinal (MPC).", example: "Konsumsi domestik sebagai penopang 53% PDB Indonesia" },
  "Produksi": { focus: "Fungsi produksi jangka pendek & panjang, produktivitas marjinal, serta efisiensi input.", example: "Hukum hasil yang semakin menurun (Law of Diminishing Returns)" },
  "Mekanisme Pasar": { focus: "Prinsip tangan tak terlihat (invisible hand) dalam mengalokasikan sumber daya secara desentralisasi.", example: "Penyesuaian otomatis harga saat terjadi kelangkaan stok pasokan" },
  "Harga": { focus: "Fungsi harga sebagai sinyal informasi kelangkaan dan instrumen penyeimbang supply-demand.", example: "Fluktuasi harga minyak mentah memicu inovasi efisiensi energi" },

  // 2 SKS (16)
  "Permintaan": { focus: "Hukum permintaan: hubungan negatif antara tingkat harga dan jumlah barang yang diminta ceteris paribus.", example: "Pergeseran kurva permintaan saat daya beli masyarakat meningkat" },
  "Penawaran": { focus: "Hukum penawaran: hubungan positif antara tingkat harga pasar dan kesediaan produsen melepas produk.", example: "Kenaikan biaya bahan baku menggeser kurva penawaran ke kiri" },
  "Keseimbangan": { focus: "Titik temu ekuilibrium pasar di mana jumlah permintaan sama dengan jumlah penawaran (Qd = Qs).", example: "Ekuilibrium harga gabah kering pasca panen raya" },
  "Elastisitas": { focus: "Derajat kepekaan kuantitas permintaan terhadap fluktuasi harga barang (Ed).", example: "Komoditas pangan pokok dan energi bersifat inelastis harga" },
  "Elastisitas Penawaran": { focus: "Responsivitas kapasitas produksi produsen terhadap perubahan harga pasar.", example: "Hasil panen perkebunan jangka pendek cenderung inelastis penawaran" },
  "Substitusi": { focus: "Hubungan barang pengganti dengan elastisitas silang positif terhadap harga komoditas terkait.", example: "Kenaikan harga daging sapi mengalihkan permintaan ke daging ayam" },
  "Surplus": { focus: "Surplus konsumen (selisih kerelaan bayar vs harga riil) dan surplus produsen.", example: "Total surplus ekonomi sebagai barometer efisiensi kesejahteraan pasar" },
  "Floor & Ceiling": { focus: "Regulasi harga batas bawah (floor price) dan harga eceran tertinggi (ceiling price/HET).", example: "Penerapan HET minyak goreng kemasan dan harga dasar gabah petani" },
  "Intervensi": { focus: "Pengaruh intervensi negara terhadap dinamika pasar dan potensi timbulnya deadweight loss.", example: "Distorsi kuota impor terhadap ketersediaan pasokan daging nasional" },
  "Pajak": { focus: "Insidensi pajak: bagaimana beban pungutan negara terbagi antara produsen dan konsumen.", example: "Penerapan kenaikan tarif PPN dan cukai hasil tembakau" },
  "Subsidi": { focus: "Bantuan fiskal pemerintah guna menekan biaya produksi dan menjaga keterjangkauan komoditas esensial.", example: "Subsidi energi listrik tarif bersubsidi dan pupuk pertanian" },
  "Utilitas": { focus: "Konsep kepuasan konsumen (Total Utility vs Marginal Utility) dan kurva indiferensi.", example: "Penurunan kepuasan tambahan (Law of Diminishing Marginal Utility)" },
  "Biaya Jangka Pendek": { focus: "Struktur Fixed Cost (FC), Variable Cost (VC), Marginal Cost (MC), dan titik impas (BEP).", example: "Perhitungan titik impas operasional pabrik manufaktur" },
  "Biaya Jangka Panjang": { focus: "Kurva biaya rata-rata jangka panjang (LRAC) dan pencapaian skala ekonomis (economies of scale).", example: "Efisiensi biaya per unit pada pabrik perakitan berskala besar" },
  "Persaingan Sempurna": { focus: "Pasar dengan produk homogen, banyak pelaku, ketiadaan hambatan masuk, dan price-taker.", example: "Pasar tradisional komoditas hortikultura di tingkat petani" },
  "Monopoli": { focus: "Pasar dengan penjual tunggal, hambatan masuk tinggi, dan kendala penentuan harga absolut.", example: "Monopoli alamiah transmisi jaringan kelistrikan nasional" },

  // 3 SKS (25)
  "Fiskal": { focus: "Kebijakan penerimaan perpajakan dan belanja APBN untuk stabilitas makroekonomi.", example: "Pelebaran ruang defisit fiskal APBN saat mitigasi krisis ekonomi" },
  "Belanja Negara": { focus: "Multiplier effect pengeluaran modal publik untuk mendorong pertumbuhan output jangka panjang.", example: "Pembangunan bendungan irigasi dan konektivitas pelabuhan laut" },
  "Moneter": { focus: "Instrumen suku bunga acuan bank sentral, giro wajib minimum, dan operasi pasar terbuka.", example: "Penyesuaian BI-Rate guna menstabilkan nilai tukar dan inflasi" },
  "Inflasi": { focus: "Laju depresiasi daya beli akibat kenaikan harga umum: demand-pull vs cost-push.", example: "Lonjakan imported inflation akibat kenaikan harga minyak mentah dunia" },
  "Deflasi": { focus: "Penurunan tingkat harga umum berkelanjutan yang berisiko memicu resesi dan penundaan belanja.", example: "Fenomena liquidity trap pada perekonomian Jepang era pasca-1990" },
  "Siklus Bisnis": { focus: "Fase ekspansi, puncak (peak), kontraksi resesi (trough), dan pemulihan output riil.", example: "Indikator leading, coincident, dan lagging dalam proyeksi ekonomi" },
  "Pengangguran": { focus: "Analisis tingkat pengangguran terbuka: friksional, struktural, musiman, dan siklikal.", example: "Program upskilling tenaga kerja menghadapi disrupsi otomatisasi" },
  "Pertumbuhan": { focus: "Kenaikan PDB riil per kapita dan model pertumbuhan ekonomi berbasis produktivitas total (TFP).", example: "Strategi pertumbuhan ekonomi 6-7% guna keluar dari Middle Income Trap" },
  "Neraca Pembayaran": { focus: "Catatan transaksi ekonomi penduduk dengan dunia luar (transaksi berjalan & neraca modal).", example: "Dampak surplus neraca perdagangan komoditas ekspor olahan nikel & CPO" },
  "Kurs": { focus: "Penentuan nilai tukar mata uang, paritas daya beli (PPP), dan mekanisme kurs mengambang terkendali.", example: "Intervensi devisa bank sentral saat penguatan indeks Dolar AS (DXY)" },
  "Tarif": { focus: "Instrumen proteksionisme perdagangan internasional melalui bea masuk dan kuota impor.", example: "Pemberlakuan bea masuk tindakan pengamanan (BMTP) untuk produk tekstil" },
  "Organisasi Internasional": { focus: "Arsitektur ekonomi global dan peranan lembaga multilateral (WTO, IMF, World Bank, OECD).", example: "Mekanisme penyelesaian sengketa ekspor komoditas di panel WTO" },
  "Ekonomi Terbuka": { focus: "Model makroekonomi terbuka (Mundell-Fleming) dan trilemma kebijakan moneter global.", example: "Keterikatan antara mobilitas arus modal, nilai tukar, dan independensi moneter" },
  "Krisis Ekonomi": { focus: "Pemicu dan resolusi krisis keuangan: likuiditas perbankan, utang luar negeri, dan krisis kepercayaan.", example: "Pelajaran krisis moneter 1998 dan penguatan rasio kecukupan modal (CAR)" },
  "Ekonomi Indonesia": { focus: "Karakteristik kepulauan berbasis konsumsi domestik, komoditas alam, dan demografi muda.", example: "Hilirisasi sumber daya alam mentah menuju produk manufaktur bernilai tinggi" },
  "Digital": { focus: "Transformasi ekonomi internet, platform marketplace, dan integrasi pembayaran nirsentuh.", example: "Adopsi standar QRIS nasional dalam ekosistem ritel dan UMKM" },
  "BUMN": { focus: "Fungsi ganda entitas usaha negara sebagai lokomotif agen pembangunan dan sumber deviden kas negara.", example: "Konsolidasi holding industri pertambangan MIND ID dan holding farmasi" },
  "UMKM": { focus: "Usaha mikro, kecil, dan menengah sebagai bantalan penyerap 97% lapangan kerja nasional.", example: "Akses pembiayaan subsidi bunga Kredit Usaha Rakyat (KUR) mikro" },
  "Industri 4.0": { focus: "Adopsi teknologi cerdas, internet of things (IoT), dan kecerdasan buatan dalam manufaktur.", example: "Implementasi automated warehouse dan predictive maintenance pabrik" },
  "Ekonomi Kreatif": { focus: "Penciptaan nilai tambah ekonomi berbasis kekayaan intelektual, budaya, dan inovasi desain.", example: "Pengembangan ekspor subsektor animasi, kriya fesyen, dan kuliner olahan" },
  "Pariwisata": { focus: "Multiplier effect pariwisata terhadap pemasukan devisa, pajak daerah, dan ekonomi rakyat.", example: "Pengembangan infrastruktur kawasan 5 Destinasi Pariwisata Super Prioritas" },
  "Ketimpangan": { focus: "Indikator disparitas pendapatan masyarakat menggunakan Koefisien Gini dan Kurva Lorenz.", example: "Ketimpangan pembangunan wilayah barat (Jawa-Sumatra) vs wilayah timur" },
  "Pemerataan": { focus: "Kebijakan jaring pengaman sosial, subsidi bersasar, dan sistem perpajakan progresif.", example: "Bantuan Program Keluarga Harapan (PKH) dan Kartu Indonesia Pintar" },
  "Dana Desa": { focus: "Desentralisasi transfer fiskal langsung untuk kemandirian ekonomi perdesaan dan BUMDes.", example: "Pembangunan irigasi desa dan lumbung pangan lokal berbasis desa" },
  "Masa Depan Ekonomi": { focus: "Mega-tren transisi energi hijau, dekarbonisasi industri, dan kecerdasan buatan.", example: "Penerapan bursa perdagangan karbon dan pajak emisi gas rumah kaca" },

  // + Praktikum (36)
  "Perilaku": { focus: "Behavioral economics: pengaruh faktor psikologis dan emosional terhadap keputusan ekonomi.", example: "Konsep bounded rationality dalam pemilihan produk keuangan ritel" },
  "Mental Accounting": { focus: "Kecenderungan manusia memisahkan uang ke dalam rekening mental yang berbeda secara irasional.", example: "Memperlakukan uang bonus akhir tahun secara lebih konsumtif dibanding gaji pokok" },
  "Overconfidence": { focus: "Bias kognitif saat pelaku pasar melebih-lebihkan akurasi estimasi dan kemampuan analisisnya.", example: "Perilaku overtrading investor pemula di bursa saham spekulatif" },
  "Herding": { focus: "Perilaku kawanan yang meniru aksi mayoritas pelaku pasar tanpa analisis fundamental.", example: "Fenomena FOMO pada reli spekulasi aset kripto dan saham gorengan" },
  "Nudge": { focus: "Desain arsitektur pilihan yang mendorong keputusan bijak tanpa paksaan larangan eksplisit.", example: "Opsi default pendaftaran otomatis keikutsertaan program dana pensiun karyawan" },
  "Platform": { focus: "Bisnis platform dua sisi (two-sided market) dengan efek jaringan (network effect) kuat.", example: "Ekosistem marketplace yang menghubungkan jutaan pedagang dan pembeli" },
  "Fintech": { focus: "Disrupsi layanan keuangan: pinjaman digital P2P, neobank, dan dompet elektronik terintegrasi.", example: "Credit scoring berbasis machine learning menggunakan rekam jejak digital" },
  "Cryptocurrency": { focus: "Aset kriptografi terdesentralisasi berbasis teknologi distributed ledger (blockchain).", example: "Volatilitas harga Bitcoin vs kegunaan stablecoin sebagai lindung nilai" },
  "Gelembung Aset": { focus: "Kenaikan harga aset melejit melampaui nilai intrinsik fundamental sebelum akhirnya meletus (crash).", example: "Sejarah gelembung Tulip Mania, Dot-com Bubble, dan Krisis Subprime Mortgage" },
  "Ekonomi Sirkular": { focus: "Model industri tertutup yang meminimalisasi limbah melalui regenerasi material daur ulang.", example: "Daur ulang komponen baterai kendaraan listrik menjadi bahan baku sel baru" },
  "Perlindungan Sosial": { focus: "Kerangka adaptif jaminan sosial ketenagakerjaan saat terjadi guncangan makro.", example: "Program Jaminan Kehilangan Pekerjaan (JKP) dan pelatihan vokasi" },
  "Ekonomi Digital": { focus: "Kontribusi sektor ekonomi berbasis internet, komputasi awan, dan data analitika.", example: "Perkiraan lonjakan GMV ekonomi digital nasional hingga ratusan miliar dolar" },
  "Green Economy": { focus: "Pola pembangunan ekonomi yang rendah emisi karbon dan ramah lingkungan hidup.", example: "Penerbitan surat berharga Green Sukuk untuk mendanai pembangkit EBT" },
  "Blue Economy": { focus: "Pemanfaatan sumber daya kelautan dan perikanan yang berkelanjutan secara ekonomi dan ekologis.", example: "Budi daya rumput laut bernilai ekspor dan modernisasi armada nelayan" },
  "Sharing Economy": { focus: "Monetisasi aset menganggur melalui kolaborasi berbagi kapasitas berbasis aplikasi digital.", example: "Penyewaan ruang kantor bersama (coworking) dan komputasi awan on-demand" },
  "Game Theory": { focus: "Model interaksi strategis matematis antarpelaku ekonomi yang saling memengaruhi.", example: "Dilema Tahanan (Prisoner's Dilemma) dalam perang harga pasar oligopoli" },
  "SDM": { focus: "Investasi modal manusia melalui pendidikan berkualitas, kesehatan prima, dan sertifikasi keahlian.", example: "Pencegahan stunting balita demi produktivitas bonus demografi 2030-2045" },
  "Asimetri Informasi": { focus: "Ketimpangan informasi antara pihak penjual dan pembeli dalam transaksi pasar.", example: "Fenomena adverse selection pada asuransi dan moral hazard perkreditan" },
  "Inovasi": { focus: "Teori Creative Destruction Schumpeter: inovasi baru menggantikan cara lama demi lonjakan efisiensi.", example: "Layanan streaming digital yang mendisrupsi industri rekaman fisik" },
  "Kontra-Siklus": { focus: "Kebijakan ekonomi yang sengaja melawan arah siklus bisnis guna meredam gejolak ekstrem.", example: "Stimulus fiskal saat resesi dan pengetatan anggaran saat ekonomi kepanasan (overheating)" },
  "Quantitative Easing": { focus: "Stimulus moneter luar biasa bank sentral dengan menyuntikkan uang langsung via pembelian obligasi.", example: "Pembelian obligasi negara skala masif oleh The Fed saat krisis likuiditas global" },
  "Ekonomi Perang": { focus: "Mobilisasi alokasi sumber daya darurat dan penyesuaian produksi saat krisis geopolitik.", example: "Kemandirian pasokan pangan dan energi di tengah embargo geopolitik dunia" },
  "Pasca-Pandemi": { focus: "Transformasi pola konsumsi dan model kerja hibrida pasca pemulihan krisis kesehatan global.", example: "Efisiensi biaya operasional perusahaan melalui sistem kerja jarak jauh (remote)" },
  "Ekonomi Global": { focus: "Integrasi rantai pasok manufaktur lintas benua, fragmentasi perdagangan, dan proteksi industri.", example: "Kebijakan friend-shoring dalam pengamanan pasokan semikonduktor global" },
  "Investasi Asing": { focus: "Penanaman Modal Asing (PMA) langsung untuk alih teknologi dan peningkatan kapasitas ekspor.", example: "Pembangunan pabrik sel baterai mobil listrik di kawasan industri terpadu" },
  "Hilirisasi": { focus: "Kebijakan melarang ekspor bahan mentah demi menciptakan nilai tambah manufaktur domestik.", example: "Peningkatan nilai ekspor olahan nikel menjadi stainless steel dan katoda baterai" },
  "CBDC": { focus: "Central Bank Digital Currency (Rupiah Digital) sebagai mata uang kedaulatan digital bank sentral.", example: "Proyek Garuda BI untuk transaksi transfer antarbank wholesale nir-gesekan" },
  "Studi Kasus Pandemi": { focus: "Evaluasi paket Pemulihan Ekonomi Nasional (PEN), restrukturisasi utang, dan bansos tunai.", example: "Mitigasi kerentanan kemiskinan ekstrem melalui bansos digital" },
  "Studi Kasus Kripto": { focus: "Pelajaran dari runtuhnya stablecoin algoritmik dan bursa derivatif kripto tak teregulasi.", example: "Urgensi pengawasan cadangan kas (proof-of-reserves) dan pemisahan dana nasabah" },
  "Studi Kasus The Fed": { focus: "Analisis dampak kenaikan agresif suku bunga acuan AS (Fed Funds Rate) terhadap emerging markets.", example: "Tekanan capital outflow dan depresiasi mata uang di negara berkembang" },
  "Studi Kasus Nikel": { focus: "Kajian empiris multiplier effect larangan ekspor bijih nikel terhadap pendapatan negara.", example: "Lonjakan penerimaan pajak dan devisa ekspor dari industri hilir nikel Morowali" },
  "Studi Kasus El Nino": { focus: "Dampak cuaca ekstrem terhadap produktivitas padi dan strategi stabilisasi stok Bulog.", example: "Operasi pasar beras SPHP untuk meredam inflasi volatile food" },
  "Studi Kasus Argentina": { focus: "Analisis hiperinflasi kronis akibat defisit anggaran yang terus dicetak uang oleh bank sentral.", example: "Krisis kepercayaan mata uang Peso dan reformasi fiskal pemotongan subsidi" },
};
